import {AMMUNITION,ARMOR_CATALOG,EQUIPMENT_CATALOG,SHIELDS,WEAPON_CATALOG,type GearRecord,type WeaponRecord,type ArmorRecord} from "./equipment-catalog";
export type EquipmentSystemic={description:string;tags:string[];consumable?:boolean;quantity?:number;durationTurns?:number;capacityLb?:number;containerFor?:string[];uses:string[];specialRules?:string[]};
const GEAR_SYSTEMICS:Record<string,EquipmentSystemic>={
backpack:{description:"A leather or heavy-cloth pack worn across the shoulders for carrying travelling gear.",tags:["container","carry"],capacityLb:50,containerFor:["general gear","rations","small treasure"],uses:["Carry equipment while keeping the hands free."]},
"belt-pouch-large":{description:"A sturdy belt pouch for coins, tools and small objects.",tags:["container","quick-access"],capacityLb:10,containerFor:["coins","small items","components"],uses:["Keep small objects readily accessible."]},
"belt-pouch-small":{description:"A compact belt pouch suited to coins and very small objects.",tags:["container","quick-access"],capacityLb:5,containerFor:["coins","small items","components"],uses:["Keep a few small objects readily accessible."]},
"sack-large":{description:"A coarse cloth sack that can hold bulky loose goods.",tags:["container","carry"],capacityLb:30,containerFor:["general gear","loot"],uses:["Carry or bundle loose objects."]},
"sack-small":{description:"A small cloth sack for provisions, coins or gathered objects.",tags:["container","carry"],capacityLb:10,containerFor:["general gear","loot"],uses:["Carry or bundle small objects."]},
"chest-small":{description:"A small rigid wooden chest suitable for protecting valuables.",tags:["container","rigid"],capacityLb:50,containerFor:["treasure","documents","general gear"],uses:["Store and protect objects; can be locked if fitted with a lock."]},
bedroll:{description:"A rolled blanket and simple bedding for sleeping away from an inn.",tags:["camp","rest"],uses:["Sleep more comfortably during wilderness or dungeon camps."]},
"rope-hemp":{description:"Fifty feet of stout hemp rope, strong but relatively heavy.",tags:["rope","climbing","binding","leverage"],uses:["Climb or descend","Tie or restrain","Secure loads","Create improvised lines or anchors"],specialRules:["Requires a suitable anchor for safe climbing or descent."]},
"rope-silk":{description:"Fifty feet of strong, light silk rope favoured by climbers and adventurers.",tags:["rope","climbing","binding","lightweight"],uses:["Climb or descend","Tie or restrain","Secure loads","Create improvised lines or anchors"]},
"lantern-bullseye":{description:"A shuttered directional lantern that throws a focused beam.",tags:["light-source","oil","directional"],uses:["Illuminate a directed area","Signal with light"],specialRules:["Requires lamp oil."]},
"lantern-hooded":{description:"A hooded oil lantern giving broad light that can be shuttered.",tags:["light-source","oil"],uses:["Illuminate an area","Hide or reveal light with the hood"],specialRules:["Requires lamp oil."]},
oil:{description:"A flask of lamp oil used primarily as fuel.",tags:["fuel","liquid","flammable"],consumable:true,quantity:1,uses:["Fuel a lantern","Create an improvised flammable hazard when the rules permit"],specialRules:["Fire interactions are resolved by the deterministic hazard engine, not by narration alone."]},
torch:{description:"A resinous wooden torch that burns with a bright open flame.",tags:["light-source","fire","consumable"],consumable:true,quantity:1,durationTurns:6,uses:["Illuminate an area","Ignite ordinary combustible material"]},
tinderbox:{description:"Flint, steel and dry tinder kept together for starting fires.",tags:["fire-starting","tool"],uses:["Light torches, lanterns, campfires and other suitable fuel."]},
crowbar:{description:"A short iron levering bar made for prying and forcing.",tags:["tool","leverage","forcing"],uses:["Pry lids or doors","Gain leverage on movable objects"],specialRules:["Can grant a situational bonus to appropriate forcing attempts when leverage is possible."]},
hammer:{description:"A compact iron-headed hammer useful for camp and climbing work.",tags:["tool","hammering"],uses:["Drive spikes or pitons","Break small brittle objects","General repairs"]},
pitons:{description:"Ten iron spikes for securing ropes, doors and temporary anchors.",tags:["tool","anchor","climbing"],consumable:true,quantity:10,uses:["Anchor rope","Spike a door","Create a temporary fixing point"],specialRules:["Hammer or equivalent tool normally required to drive securely."]},
pole:{description:"A straight ten-foot wooden pole, awkward to carry but invaluable for probing suspicious spaces.",tags:["probe","reach","trap-testing"],uses:["Probe floors, ceilings or openings from a distance","Reach or push light objects"],specialRules:["Does not automatically detect a trap; it changes how the attempted interaction is resolved."]},
mirror:{description:"A small polished steel mirror.",tags:["reflection","viewing","signal"],uses:["Look around corners without exposing the whole body","Reflect light","Inspect otherwise awkward angles"]},
chalk:{description:"A stick of pale chalk for marking stone, wood and other dry surfaces.",tags:["marking","navigation"],consumable:true,uses:["Mark routes, doors or objects","Leave simple messages or symbols"]},
rations:{description:"Preserved trail food sufficient for roughly one person for one week.",tags:["food","consumable"],consumable:true,quantity:7,uses:["Provide one day of ordinary travelling food per ration unit."]},
waterskin:{description:"A leather drinking vessel carried on a strap or belt.",tags:["container","water","liquid"],capacityLb:4,containerFor:["water","other ordinary drinkable liquids"],uses:["Carry drinking water or another suitable liquid."]},
"holy-symbol-wood":{description:"A simple wooden emblem used in religious observance.",tags:["holy-symbol","priest","focus"],uses:["Serve as a priestly religious focus when appropriate to the character's faith."]},
"holy-symbol-silver":{description:"A finely made silver religious emblem.",tags:["holy-symbol","priest","valuable","focus"],uses:["Serve as a priestly religious focus when appropriate to the character's faith."]},
"spellbook-blank":{description:"A bound volume of high-quality pages prepared for arcane notation.",tags:["spellbook","wizard","writing"],uses:["Record wizard spells when the spell-learning rules allow it."]},
"thieves-tools":{description:"A compact roll of picks, probes, small files and specialist tools.",tags:["thief","lock","trap","tool"],uses:["Attempt suitable lock manipulation","Attempt suitable mechanical trap work"],specialRules:["Possessing tools does not guarantee success; thief ability checks still resolve the attempt."]}}
function weaponSystemic(w:WeaponRecord):EquipmentSystemic{return{description:`${w.name} is a ${w.size==="S"?"small":w.size==="M"?"medium-sized":"large"} weapon.`,tags:["weapon",w.type,w.size,w.range?"ranged":"melee",w.twoHanded?"two-handed":"one-handed"],uses:[w.range?"Make ranged attacks within its range bands":"Make melee attacks"],specialRules:[`Speed factor ${w.speed}.`,`Damage S/M ${w.damageSM}; damage Large ${w.damageL}.`,...(w.rof?[`Rate of fire ${w.rof}.`]:[]),...(w.ammoId?[`Requires ${w.ammoId} ammunition.`]:[]),...(w.notes?[w.notes]:[])]}}
function armorSystemic(a:ArmorRecord):EquipmentSystemic{return{description:`${a.name} is protective armour with base AC ${a.baseAc} before shield and Dexterity adjustments.`,tags:["armour","protection"],uses:["Reduce vulnerability to attacks while worn"],specialRules:[...(a.movementNote?[a.movementNote]:[]),...(a.notes?[a.notes]:[])]}}
export function systemicForGear(item:GearRecord):EquipmentSystemic{return GEAR_SYSTEMICS[item.id]??{description:item.notes??`${item.name}, a piece of ${item.category} equipment.`,tags:[item.category],capacityLb:item.capacityLb,uses:["Use when a plausible game action calls for this item."],specialRules:item.notes?[item.notes]:undefined}}
export function enrichedEquipmentCatalogue(){return{weapons:WEAPON_CATALOG.map(item=>({...item,systemic:weaponSystemic(item)})),armour:ARMOR_CATALOG.map(item=>({...item,systemic:armorSystemic(item)})),shields:SHIELDS.map(item=>({...item,systemic:{description:`${item.name} is a carried shield providing an AC bonus when applicable.`,tags:["shield","protection"],uses:["Defend against eligible attacks"]} as EquipmentSystemic})),ammunition:AMMUNITION.map(item=>({...item,systemic:{description:`${item.name} is ammunition consumed when used with a compatible missile weapon.`,tags:["ammunition","consumable"],consumable:true,quantity:item.quantity,uses:["Supply a compatible ranged weapon"]} as EquipmentSystemic})),gear:EQUIPMENT_CATALOG.map(item=>({...item,systemic:systemicForGear(item)}))}}
