import type {ClassId} from "./rules";
import {PRIEST_MAJOR_SPHERES,type PriestSphere,type WizardSpell} from "./magic-rules";

export type MagicTradition="wizard"|"priest";
export type SaveType="none"|"spell"|"breath"|"paralyzation"|"special";
export type SpellComponent="V"|"S"|"M";
export type SpellTarget="self"|"creature"|"creatures"|"object"|"point"|"area";
export type SpellRecord={
 id:string;name:string;tradition:MagicTradition;level:number;school?:WizardSpell["school"];spheres?:PriestSphere[];
 range:string;duration:string;castingTime:number;components:SpellComponent[];area:string;save:SaveType;magicResistance:boolean;
 target:SpellTarget;description:string;tags:string[];damage?:string;healing?:string;scaling?:string;material?:string;systemic:{kind:string;params?:Record<string,string|number|boolean>};
};

export const SPELL_CATALOG:SpellRecord[]=[
{id:"armor",name:"Armor",tradition:"wizard",level:1,school:"Conjuration",range:"Touch",duration:"2 hours/level",castingTime:1,components:["V","S","M"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Creates a protective magical force around the subject.",tags:["defense","ac"],material:"A piece of cured leather",systemic:{kind:"set-ac",params:{baseAc:6}}},
{id:"burning-hands",name:"Burning Hands",tradition:"wizard",level:1,school:"Alteration",range:"0",duration:"Instant",castingTime:1,components:["V","S"],area:"5-ft fan",save:"special",magicResistance:true,target:"area",description:"A fan of flame erupts from the caster's hands.",tags:["fire","damage","area"],damage:"1d3+2 per level, max +20",scaling:"Damage increases with caster level.",systemic:{kind:"damage-area",params:{type:"fire"}}},
{id:"charm-person",name:"Charm Person",tradition:"wizard",level:1,school:"Enchantment",range:"120 yd",duration:"Special",castingTime:1,components:["V","S"],area:"1 person",save:"spell",magicResistance:true,target:"creature",description:"Magically influences a humanoid's attitude toward the caster.",tags:["charm","control"],systemic:{kind:"condition",params:{condition:"charmed"}}},
{id:"color-spray",name:"Color Spray",tradition:"wizard",level:1,school:"Alteration",range:"0",duration:"Instant",castingTime:1,components:["V","S","M"],area:"Cone",save:"special",magicResistance:true,target:"area",description:"A vivid cone of clashing colours overwhelms nearby creatures.",tags:["illusion","control","area"],systemic:{kind:"hd-based-control"}},
{id:"comprehend-languages",name:"Comprehend Languages",tradition:"wizard",level:1,school:"Alteration",range:"Touch",duration:"5 rounds/level",castingTime:1,components:["V","S","M"],area:"1 written or spoken source",save:"none",magicResistance:false,target:"object",description:"Allows the caster to understand otherwise unknown languages.",tags:["language","utility"],systemic:{kind:"language-understanding"}},
{id:"detect-magic-w",name:"Detect Magic",tradition:"wizard",level:1,school:"Divination",range:"0",duration:"2 rounds/level",castingTime:1,components:["V","S"],area:"60-ft path",save:"none",magicResistance:false,target:"area",description:"Reveals magical auras in the caster's field of attention.",tags:["detection","magic"],systemic:{kind:"detect-magic"}},
{id:"feather-fall",name:"Feather Fall",tradition:"wizard",level:1,school:"Alteration",range:"10 yd/level",duration:"1 round/level",castingTime:1,components:["V"],area:"1 creature/level",save:"none",magicResistance:false,target:"creatures",description:"Slows falling creatures so they descend safely.",tags:["movement","falling","reaction"],systemic:{kind:"fall-protection"}},
{id:"grease",name:"Grease",tradition:"wizard",level:1,school:"Conjuration",range:"10 yd",duration:"3 rounds + 1 round/level",castingTime:1,components:["V","S","M"],area:"10-ft square",save:"special",magicResistance:false,target:"area",description:"Covers a surface or object in magically slick grease.",tags:["control","terrain"],systemic:{kind:"slippery-area"}},
{id:"identify",name:"Identify",tradition:"wizard",level:1,school:"Divination",range:"Touch",duration:"1 round/level",castingTime:10,components:["V","S","M"],area:"1 item",save:"none",magicResistance:false,target:"object",description:"Reveals properties of a magical item under controlled conditions.",tags:["identify","magic-item"],systemic:{kind:"identify-item"}},
{id:"light-w",name:"Light",tradition:"wizard",level:1,school:"Alteration",range:"60 yd",duration:"1 turn/level",castingTime:1,components:["V","S"],area:"20-ft radius",save:"special",magicResistance:false,target:"point",description:"Creates a bright magical light on a point or object.",tags:["light","utility"],systemic:{kind:"light",params:{radiusFt:20}}},
{id:"magic-missile",name:"Magic Missile",tradition:"wizard",level:1,school:"Evocation",range:"60 yd + 10 yd/level",duration:"Instant",castingTime:1,components:["V","S"],area:"1 or more creatures",save:"none",magicResistance:true,target:"creatures",description:"Creates unerring bolts of magical force.",tags:["force","damage"],damage:"1d4+1 per missile",scaling:"One missile at 1st level, then additional missiles at higher level thresholds.",systemic:{kind:"auto-hit-damage"}},
{id:"phantasmal-force",name:"Phantasmal Force",tradition:"wizard",level:1,school:"Illusion",range:"60 yd + 10 yd/level",duration:"Special",castingTime:1,components:["V","S","M"],area:"400 sq ft + 100 sq ft/level",save:"special",magicResistance:false,target:"area",description:"Creates a sensory illusion shaped by the caster.",tags:["illusion","creative"],systemic:{kind:"illusion"}},
{id:"protection-from-evil-w",name:"Protection from Evil",tradition:"wizard",level:1,school:"Abjuration",range:"Touch",duration:"2 rounds/level",castingTime:1,components:["V","S","M"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Creates a ward against certain hostile creatures and influences.",tags:["protection","ward"],systemic:{kind:"ward"}},
{id:"read-magic",name:"Read Magic",tradition:"wizard",level:1,school:"Divination",range:"0",duration:"2 rounds/level",castingTime:1,components:["V","S","M"],area:"Special",save:"none",magicResistance:false,target:"object",description:"Allows the caster to read magical writing.",tags:["language","magic"],systemic:{kind:"read-magic"}},
{id:"shield",name:"Shield",tradition:"wizard",level:1,school:"Evocation",range:"0",duration:"5 rounds/level",castingTime:1,components:["V","S"],area:"Caster",save:"none",magicResistance:false,target:"self",description:"Creates an invisible barrier that improves defense.",tags:["defense","missile"],systemic:{kind:"shield-defense"}},
{id:"sleep",name:"Sleep",tradition:"wizard",level:1,school:"Enchantment",range:"60 yd",duration:"5 rounds/level",castingTime:1,components:["V","S","M"],area:"15-ft radius",save:"none",magicResistance:true,target:"area",description:"Puts a limited number of low-hit-die creatures into magical sleep.",tags:["sleep","control","area"],systemic:{kind:"sleep-hd"}},
{id:"spider-climb",name:"Spider Climb",tradition:"wizard",level:1,school:"Alteration",range:"Touch",duration:"3 rounds + 1 round/level",castingTime:1,components:["V","S","M"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Allows movement across walls and ceilings like a spider.",tags:["movement","climbing"],systemic:{kind:"climb-surface"}},
{id:"unseen-servant",name:"Unseen Servant",tradition:"wizard",level:1,school:"Conjuration",range:"0",duration:"1 hour + 1 turn/level",castingTime:1,components:["V","S","M"],area:"30-ft radius",save:"none",magicResistance:false,target:"area",description:"Creates an invisible force able to perform simple mundane tasks.",tags:["utility","force"],systemic:{kind:"servant"}},
{id:"ventriloquism",name:"Ventriloquism",tradition:"wizard",level:1,school:"Illusion",range:"10 yd/level",duration:"4 rounds + 1 round/level",castingTime:1,components:["V","M"],area:"1 source",save:"special",magicResistance:false,target:"point",description:"Makes the caster's voice seem to come from another location.",tags:["illusion","sound"],systemic:{kind:"false-sound"}},
{id:"knock",name:"Knock",tradition:"wizard",level:2,school:"Alteration",range:"60 yd",duration:"Instant",castingTime:1,components:["V"],area:"1 door/object",save:"none",magicResistance:false,target:"object",description:"Opens many mundane closures and certain magical locks.",tags:["utility","locks"],systemic:{kind:"open-lock"}},
{id:"levitate",name:"Levitate",tradition:"wizard",level:2,school:"Alteration",range:"20 yd/level",duration:"1 turn/level",castingTime:2,components:["V","S","M"],area:"1 creature/object",save:"special",magicResistance:true,target:"object",description:"Raises or lowers a creature or object vertically.",tags:["movement","vertical"],systemic:{kind:"levitate"}},
{id:"mirror-image",name:"Mirror Image",tradition:"wizard",level:2,school:"Illusion",range:"0",duration:"3 rounds/level",castingTime:1,components:["V","S"],area:"Caster",save:"none",magicResistance:false,target:"self",description:"Creates illusory duplicates that confuse attackers.",tags:["illusion","defense"],systemic:{kind:"decoys"}},
{id:"web",name:"Web",tradition:"wizard",level:2,school:"Evocation",range:"5 yd/level",duration:"2 turns/level",castingTime:2,components:["V","S","M"],area:"8,000 cubic ft",save:"special",magicResistance:false,target:"area",description:"Fills an area with strong sticky strands that impede movement.",tags:["control","terrain"],systemic:{kind:"restraining-area"}},
{id:"fireball",name:"Fireball",tradition:"wizard",level:3,school:"Evocation",range:"10 yd + 10 yd/level",duration:"Instant",castingTime:3,components:["V","S","M"],area:"20-ft radius",save:"spell",magicResistance:true,target:"point",description:"Detonates an explosive sphere of magical fire.",tags:["fire","damage","area"],damage:"1d6/level",scaling:"Maximum 10d6 in this core profile.",systemic:{kind:"damage-area",params:{type:"fire",maxDice:10}}},
{id:"fly",name:"Fly",tradition:"wizard",level:3,school:"Alteration",range:"Touch",duration:"1 turn/level + variable",castingTime:3,components:["V","S","M"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Grants controlled flight for a limited duration.",tags:["movement","flight"],systemic:{kind:"flight"}},
{id:"haste",name:"Haste",tradition:"wizard",level:3,school:"Alteration",range:"60 yd",duration:"3 rounds + 1 round/level",castingTime:3,components:["V","S","M"],area:"1 creature/level",save:"none",magicResistance:false,target:"creatures",description:"Accelerates allies, improving movement and action rate.",tags:["buff","speed"],systemic:{kind:"haste"}},
{id:"lightning-bolt",name:"Lightning Bolt",tradition:"wizard",level:3,school:"Evocation",range:"40 yd + 10 yd/level",duration:"Instant",castingTime:3,components:["V","S","M"],area:"Line",save:"spell",magicResistance:true,target:"area",description:"Projects a powerful bolt of electricity through a line.",tags:["electricity","damage","area"],damage:"1d6/level",scaling:"Maximum 10d6 in this core profile.",systemic:{kind:"damage-line",params:{type:"electricity",maxDice:10}}},
{id:"dispel-magic-w",name:"Dispel Magic",tradition:"wizard",level:3,school:"Abjuration",range:"120 yd",duration:"Instant",castingTime:3,components:["V","S"],area:"30-ft cube",save:"none",magicResistance:false,target:"area",description:"Attempts to end active magical effects in an area or on a target.",tags:["dispel","magic"],systemic:{kind:"dispel"}},
{id:"dimension-door",name:"Dimension Door",tradition:"wizard",level:4,school:"Alteration",range:"0",duration:"Instant",castingTime:1,components:["V"],area:"Caster and carried gear",save:"none",magicResistance:false,target:"self",description:"Instantly relocates the caster a limited distance.",tags:["teleport","movement"],systemic:{kind:"teleport-short"}},
{id:"stoneskin",name:"Stoneskin",tradition:"wizard",level:4,school:"Alteration",range:"Touch",duration:"Special",castingTime:1,components:["V","S","M"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Protects the subject from a limited number of physical attacks.",tags:["defense","physical"],systemic:{kind:"absorb-hits"}},
{id:"teleport",name:"Teleport",tradition:"wizard",level:5,school:"Alteration",range:"Touch",duration:"Instant",castingTime:2,components:["V"],area:"Caster plus limited load",save:"none",magicResistance:false,target:"creature",description:"Transports the caster and companions instantly to a distant known location, with risk based on familiarity.",tags:["teleport","travel"],systemic:{kind:"teleport"}},
{id:"disintegrate",name:"Disintegrate",tradition:"wizard",level:6,school:"Alteration",range:"5 yd/level",duration:"Instant",castingTime:6,components:["V","S","M"],area:"1 creature/object",save:"spell",magicResistance:true,target:"object",description:"Attempts to reduce a creature or object to dust.",tags:["destruction"],systemic:{kind:"disintegrate"}},
{id:"finger-of-death",name:"Finger of Death",tradition:"wizard",level:7,school:"Necromancy",range:"60 yd",duration:"Instant",castingTime:5,components:["V","S"],area:"1 creature",save:"special",magicResistance:true,target:"creature",description:"Channels lethal necromantic force at a single target.",tags:["death","necromancy"],systemic:{kind:"death-effect"}},
{id:"maze",name:"Maze",tradition:"wizard",level:8,school:"Conjuration",range:"5 yd/level",duration:"Special",castingTime:3,components:["V","S"],area:"1 creature",save:"none",magicResistance:true,target:"creature",description:"Banishes a creature into an extradimensional labyrinth for a duration based on intellect.",tags:["banish","control"],systemic:{kind:"maze"}},
{id:"time-stop",name:"Time Stop",tradition:"wizard",level:9,school:"Alteration",range:"0",duration:"Very short",castingTime:9,components:["V"],area:"Caster",save:"none",magicResistance:false,target:"self",description:"Briefly isolates the caster from normal time.",tags:["time","high-magic"],systemic:{kind:"time-stop"}},

{id:"bless",name:"Bless",tradition:"priest",level:1,spheres:["All","Combat"],range:"60 yd",duration:"6 rounds",castingTime:1,components:["V","S","M"],area:"50-ft cube",save:"none",magicResistance:false,target:"area",description:"Bolsters allies' morale and combat effectiveness.",tags:["buff","combat"],systemic:{kind:"attack-morale-buff"}},
{id:"command",name:"Command",tradition:"priest",level:1,spheres:["Charm"],range:"30 yd",duration:"1 round",castingTime:1,components:["V"],area:"1 creature",save:"spell",magicResistance:true,target:"creature",description:"Compels a creature to obey a single brief command if it fails to resist.",tags:["control","charm"],systemic:{kind:"command"}},
{id:"cure-light-wounds",name:"Cure Light Wounds",tradition:"priest",level:1,spheres:["Healing"],range:"Touch",duration:"Instant",castingTime:5,components:["V","S"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Restores a small amount of lost hit points.",tags:["healing"],healing:"1d8",systemic:{kind:"heal"}},
{id:"detect-magic-p",name:"Detect Magic",tradition:"priest",level:1,spheres:["Divination"],range:"0",duration:"1 turn",castingTime:1,components:["V","S","M"],area:"30-ft path",save:"none",magicResistance:false,target:"area",description:"Reveals magical auras nearby.",tags:["detection","magic"],systemic:{kind:"detect-magic"}},
{id:"entangle",name:"Entangle",tradition:"priest",level:1,spheres:["Plant"],range:"80 yd",duration:"1 turn",castingTime:4,components:["V","S","M"],area:"40-ft cube",save:"special",magicResistance:false,target:"area",description:"Causes plants to grasp and hinder creatures in an area.",tags:["plant","control","terrain"],systemic:{kind:"restraining-area"}},
{id:"faerie-fire",name:"Faerie Fire",tradition:"priest",level:1,spheres:["Sun"],range:"80 yd",duration:"4 rounds/level",castingTime:4,components:["V","M"],area:"Several creatures/objects",save:"none",magicResistance:false,target:"creatures",description:"Outlines targets in pale light, making them easier to see and strike.",tags:["light","debuff"],systemic:{kind:"outline-target"}},
{id:"sanctuary",name:"Sanctuary",tradition:"priest",level:1,spheres:["Protection"],range:"Touch",duration:"2 rounds + 1 round/level",castingTime:4,components:["V","S","M"],area:"1 creature",save:"special",magicResistance:false,target:"creature",description:"Makes it difficult for hostile creatures to directly attack the protected subject.",tags:["protection"],systemic:{kind:"sanctuary"}},
{id:"silence-15",name:"Silence 15' Radius",tradition:"priest",level:2,spheres:["Guardian"],range:"120 yd",duration:"2 rounds/level",castingTime:5,components:["V","S"],area:"15-ft radius",save:"special",magicResistance:false,target:"point",description:"Suppresses sound in a radius, preventing ordinary speech and verbal spell components.",tags:["silence","anti-magic","area"],systemic:{kind:"silence",params:{radiusFt:15}}},
{id:"hold-person",name:"Hold Person",tradition:"priest",level:2,spheres:["Charm"],range:"120 yd",duration:"2 rounds/level",castingTime:5,components:["V","S","M"],area:"Up to 4 persons",save:"spell",magicResistance:true,target:"creatures",description:"Paralyzes humanoid targets that fail to resist.",tags:["paralysis","control"],systemic:{kind:"hold"}},
{id:"spiritual-hammer",name:"Spiritual Hammer",tradition:"priest",level:2,spheres:["Combat"],range:"30 yd/level",duration:"3 rounds + 1 round/level",castingTime:5,components:["V","S","M"],area:"1 magical weapon",save:"none",magicResistance:false,target:"creature",description:"Creates a floating force weapon that attacks at the priest's direction.",tags:["force","combat"],systemic:{kind:"summoned-weapon"}},
{id:"prayer",name:"Prayer",tradition:"priest",level:3,spheres:["Combat"],range:"0",duration:"1 round/level",castingTime:6,components:["V","S","M"],area:"60-ft radius",save:"none",magicResistance:false,target:"area",description:"Blesses allies and hinders foes in the surrounding area.",tags:["buff","debuff","area"],systemic:{kind:"prayer"}},
{id:"dispel-magic-p",name:"Dispel Magic",tradition:"priest",level:3,spheres:["Protection"],range:"60 yd",duration:"Instant",castingTime:6,components:["V","S"],area:"30-ft cube",save:"none",magicResistance:false,target:"area",description:"Attempts to end active magical effects.",tags:["dispel","magic"],systemic:{kind:"dispel"}},
{id:"neutralize-poison",name:"Neutralize Poison",tradition:"priest",level:4,spheres:["Healing"],range:"Touch",duration:"Instant",castingTime:7,components:["V","S"],area:"1 creature/object",save:"none",magicResistance:false,target:"creature",description:"Neutralizes most ordinary poisons affecting a target or substance.",tags:["healing","poison"],systemic:{kind:"remove-poison"}},
{id:"cure-serious-wounds",name:"Cure Serious Wounds",tradition:"priest",level:4,spheres:["Healing"],range:"Touch",duration:"Instant",castingTime:7,components:["V","S"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Restores a larger amount of lost hit points.",tags:["healing"],healing:"2d8+1",systemic:{kind:"heal"}},
{id:"flame-strike",name:"Flame Strike",tradition:"priest",level:5,spheres:["Combat","Sun"],range:"60 yd",duration:"Instant",castingTime:8,components:["V","S","M"],area:"5-ft radius x 30-ft column",save:"spell",magicResistance:true,target:"point",description:"Calls down a vertical column of divine flame.",tags:["fire","damage","area"],damage:"6d8",systemic:{kind:"damage-area",params:{type:"fire"}}},
{id:"heal",name:"Heal",tradition:"priest",level:6,spheres:["Healing"],range:"Touch",duration:"Instant",castingTime:1,components:["V","S"],area:"1 creature",save:"none",magicResistance:false,target:"creature",description:"Restores nearly all lost hit points and remedies several conditions.",tags:["healing","restoration"],systemic:{kind:"major-heal"}},
{id:"resurrection",name:"Resurrection",tradition:"priest",level:7,spheres:["Necromantic"],range:"Touch",duration:"Permanent",castingTime:1,components:["V","S","M"],area:"1 dead creature",save:"special",magicResistance:false,target:"creature",description:"Returns a dead creature to life subject to survival limits and campaign conditions.",tags:["resurrection","death"],systemic:{kind:"resurrection"}},
];

export const MAGIC_RULES_PROFILE={
 preparation:{wizard:"Wizard spells must be known in the spellbook and memorized into available slots after sufficient rest/study.",priest:"Priests choose permitted spells from accessible spheres and memorize them into available slots after prayer/rest."},
 casting:{initiative:"Casting time is added to the caster's initiative result in the detailed combat resolver.",interruption:"If the caster is successfully hit or otherwise disrupted before the spell resolves, the spell is lost unless a specific effect says otherwise.",verbal:"V components fail in magical silence or when speech is impossible.",somatic:"S components require sufficient freedom of movement and usable hands.",material:"M components require possession of a suitable component; consumed components are removed when the spell says so."},
 resistance:{saves:"Saving throws use the spell record's save field and target's current save values.",magicResistance:"When enabled for a spell, magic resistance is checked before the normal saving throw unless a specific effect overrides it."},
 memorization:{spentOnCast:true,restToRecover:true,duplicatePreparation:true},
 catalogueVersion:"core-pseudo-2e-magic-v2"
};

export function spellsForClass(classIds:ClassId[],level:number){
 const wizard=classIds.includes("mage")||classIds.includes("illusionist"); const priest=classIds.includes("cleric")||classIds.includes("druid");
 return SPELL_CATALOG.filter(s=>s.level===level&&((s.tradition==="wizard"&&wizard)||(s.tradition==="priest"&&priest))).filter(s=>{
  if(s.tradition==="priest"){const cls=classIds.includes("druid")?"druid":"cleric";return (s.spheres??[]).some(sp=>PRIEST_MAJOR_SPHERES[cls].includes(sp));}
  if(classIds.includes("illusionist")&&["Necromancy","Evocation","Abjuration"].includes(s.school??""))return false;
  return true;
 });
}
export function spellByName(name:string){return SPELL_CATALOG.find(s=>s.name===name)||null;}
export function canCastPrepared(spell:SpellRecord,prepared:string[],conditions:{silenced?:boolean;handsFree?:boolean;hasMaterial?:boolean}){
 if(!prepared.includes(spell.name))return{ok:false,reason:"Spell is not memorized."};
 if(spell.components.includes("V")&&conditions.silenced)return{ok:false,reason:"A verbal component cannot be completed in silence."};
 if(spell.components.includes("S")&&conditions.handsFree===false)return{ok:false,reason:"A somatic component cannot be completed."};
 if(spell.components.includes("M")&&conditions.hasMaterial===false)return{ok:false,reason:"Required material component is missing."};
 return{ok:true,reason:"Ready to cast."};
}
